$script:Images = @{
    "VBR_Server" = "VBR_server.png"
    "VBR_Repository" = "VBR_Repository.png"
    "VBR_Deduplicating_Storage" = "Deduplicating_Storage.png"
    "VBR_Linux_Repository" = "Linux_Repository.png"
    "VBR_Windows_Repository" = "Windows_Repository.png"
    "VBR_Cloud_Repository" = "Cloud_Repository.png"
    "VBR_Server_DB" = "Microsoft_SQL_DB.png"
    "VBR_Proxy_Server" = "Proxy_Server.png"
    "VBR_Wan_Accel" = "WAN_accelerator.png"
    "VBR_SOBR" = "Scale-out_Backup_Repository.png"
    "VBR_LOGO" = "Veeam_logo.png"
    "VBR_No_Icon" = "no_icon.png"
    'VBR_Storage_NetApp' = "Storage_NetApp.png"
    'VBR_vCenter_Server' = 'vCenter_server.png'
    'VBR_ESXi_Server' = 'ESXi_host.png'
    'VBR_HyperV_Server' = 'Hyper-V_host.png'
    'VBR_Server_EM' = 'Veeam_Backup_Enterprise_Manager.png'
    'VBR_Tape_Server' = 'Tape_Server.png'
    'VBR_Tape_Library' = 'Tape_Library.png'
    'VBR_Tape_Drive' = 'Tape_Drive.png'
    "VBR_Server_DB_PG" = "PostGre_SQL_DB.png"
    "VBR_LOGO_Footer" = "verified_recoverability.png"
    "VBR_AGENT_Container" = "Folder.png"
    "VBR_AGENT_AD" = "Server.png"
    "VBR_AGENT_MC" = "Task list.png"
    "VBR_AGENT_IC" = "Workstation.png"
    "VBR_AGENT_CSV" = "CSV_Computers.png"
    "VBR_AGENT_AD_Logo" = "Microsoft Active Directory.png"
    "VBR_AGENT_CSV_Logo" = "File.png"
    "VBR_AGENT_Server" = "Server_with_Veeam_Agent.png"

}