name: Bug Report
description: File a bug report
title: "[BUG]"
labels: ["bug"]
assignees:
  - rebelinux
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: >-
        Please provide a clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: output-log-generation
    attributes:
      label: Log Generation
      description: >-
        Please provide the Output.log as described in [Run cmdlet with debugging options](https://github.com/rebelinux/Veeam.Diagrammer/wiki/Run-cmdlet-with-debugging-options). Attach the file in the text area.
      placeholder: |-
        Drag & drop the file in the Here.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: >-
        Please provide a detailed list of steps to reproduce the bug.
      placeholder: |-
        1. ....
        2. ....
        3. ....
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: >-
        Please attach any screenshots to help explain the problem.  Please ensure that you obscure any sensitive information.
      placeholder: |-
        Drag and drop screenshots here.
  - type: textarea
    id: operating-system
    attributes:
      label: Operating System
      description: Please provide information about the operating system are you using.
      placeholder: macOS Big Sur, Windows 10, Ubuntu 20.04 LTS
    validations:
      required: true
  - type: textarea
    id: powershell-version
    attributes:
      label: PowerShell Version
      description: Please provide information about the PowerShell version you are using. Please provide the output from the following PowerShell command `$PSVersionTable`.
      placeholder: $PSVersionTable
    validations:
      required: true
  - type: textarea
    id: powershell-modules
    attributes:
      label: PowerShell Modules
      description: Please provide information about the PowerShell modules are you using. Please provide the output from the following PowerShell command `Get-Module -ListAvailable @("Veeam.Diagrammer";"PSGraph") | Select Name, Version`
      placeholder: Get-Module -ListAvailable @("Veeam.Diagrammer";"PSGraph") | Select Name, Version
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      description: >-
        Please ensure your bug report fulfills all of the following requirements.
        If you are unsure of what a specific requirement means, please follow the links to learn about it and understand why it is necessary before submitting.
      options:
        - label: >-
            I have read and followed the [bug reporting guidelines](https://github.com/rebelinux/Veeam.Diagrammer/blob/dev/CONTRIBUTING.md).
          required: true
        - label: >-
            I have read [the documentation](https://github.com/rebelinux/Veeam.Diagrammer/blob/dev/README.md),
            and referred to the [known issues](https://github.com/rebelinux/Veeam.Diagrammer/?tab=readme-ov-file#x-known-issues) before submitting this bug report.
          required: true
        - label: >-
            I have checked for previously opened & closed [issues](https://github.com/rebelinux/Veeam.Diagrammer/issues) before submitting this bug report.
          required: true
