name: Change Request
description: Request a new change or an improvement
labels: ["change request"]
assignees:
  - rebelinux
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        Please provide a detailed description of your idea so that the project maintainers and contributors can fully understand what change, change, or improvement you are proposing.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: This field is optional. You may provide additional context for the idea you wish to propose. You may wish to include links to any related [issues](https://github.com/rebelinux/Veeam.Diagrammer/issues) or other relevant information.
  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      description: >-
        Please ensure your change request fulfills all of the following requirements.
        If you are unsure of what a specific requirement means, please follow the links to learn about it and understand why it is necessary before submitting.
      options:
        - label: >-
            I have read [the documentation](https://github.com/rebelinux/Veeam.Diagrammer/blob/dev/README.md),
            and referred to the [known issues](https://github.com/rebelinux/Veeam.Diagrammer/?tab=readme-ov-file#x-known-issues) before submitting this change request.
          required: true
        - label: >-
            I have checked for previously opened & closed [issues](https://github.com/rebelinux/Veeam.Diagrammer/issues) before submitting this change request.
          required: true
